### ISSUE TITLE
OOP hova bújt el?

### ISSUE THREAD

**Issue by HornyakBence** [kovacskornel/TLOG16Java#1]
### OOP elveket szinte sehol sem használod UI közben, ez a köv fejezetben úgy is ki fog jönni, ha nem javítod ki.
A getterek setterek nem véletlen lettek kitalálva :smile: .

### Task
- 2 db subclassod ami felesleges és csak nehezíti a dolgokat, HA követed az OOP elveket.
- a Stringes splitet gondold át, hogy hogy is működik. 
### TimeLogger
- Fontos OOP elv(ek) hiányoznak
### UI
- OOP OOP jah meg OOP kéne bele... :smile: 
### WorkDay
- OOP 
### WorkMonth
- a newMonth -ot gondold át
- OOP

# Sorry for the long post here is a potato :sweet_potato:

**Comment by kovacskornel** [comment]
Fixed. Ja meg fixed. minden jó lett :100: % javítva :dancing_men:
